<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

namespace Chat\proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>chat.proto.ChatRequest</code>
 */
class ChatRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.chat.proto.RequestType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>uint32 sending_time = 2;</code>
     */
    private $sending_time = 0;
    /**
     * Generated from protobuf field <code>.chat.proto.Body body = 3;</code>
     */
    private $body = null;
    /**
     * Generated from protobuf field <code>.chat.proto.Info info = 4;</code>
     */
    private $info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int $sending_time
     *     @type \Chat\proto\Body $body
     *     @type \Chat\proto\Info $info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Chat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.chat.proto.RequestType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.chat.proto.RequestType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Chat\proto\RequestType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sending_time = 2;</code>
     * @return int
     */
    public function getSendingTime()
    {
        return $this->sending_time;
    }

    /**
     * Generated from protobuf field <code>uint32 sending_time = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSendingTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->sending_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.chat.proto.Body body = 3;</code>
     * @return \Chat\proto\Body
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>.chat.proto.Body body = 3;</code>
     * @param \Chat\proto\Body $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkMessage($var, \Chat\proto\Body::class);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.chat.proto.Info info = 4;</code>
     * @return \Chat\proto\Info
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>.chat.proto.Info info = 4;</code>
     * @param \Chat\proto\Info $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Chat\proto\Info::class);
        $this->info = $var;

        return $this;
    }

}

