<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

namespace Chat\proto;

/**
 * Protobuf type <code>chat.proto.RequestType</code>
 */
class RequestType
{
    /**
     * Generated from protobuf enum <code>RequestType_UNKNOWN = 0;</code>
     */
    const RequestType_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>RequestType_LOGIN = 1;</code>
     */
    const RequestType_LOGIN = 1;
    /**
     * Generated from protobuf enum <code>RequestType_MESSAGE = 2;</code>
     */
    const RequestType_MESSAGE = 2;
    /**
     * Generated from protobuf enum <code>RequestType_FILE = 3;</code>
     */
    const RequestType_FILE = 3;
}

